# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56fa7c76e47ac76b5673cd2c3ba41716528c4c793e92aad75999d5ca7b0e26dc68a2996a03a02423954678d515d7592bde73d36eb6507cce04bc2dd07114d9a2

test:
  secret_key_base: b740b88b9feed6a0139d31dd5478551dd1b4651685f6fdd4bc0d74ae708061d9a39182c52b9cd0216ef696884f9a2e707e7faa420380fbc702ce4f5ad84ab8c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
